import { useSettingsStore } from '../store/settingsStore';

const copy = {
  en: {
    tabs: {
      home: 'Home',
      calculator: 'Calculator',
      calculatorShort: 'Calc',
      converter: 'Converter',
      time: 'Time',
      todo: 'Todo',
      more: 'More',
    },
    home: {
      title: 'Home',
      sectionTitle: 'Utilities',
      notesLabel: 'Notes',
      historyLabel: 'History',
      enabled: 'Enabled',
      disabled: 'Disabled',
      quickActions: [
        { title: 'Converter', subtitle: 'Units, currency, bases' },
        { title: 'Todo', subtitle: 'Plan, reorder, complete' },
        { title: 'Time', subtitle: 'Clocks, timer, stopwatch' },
        { title: 'More', subtitle: 'Health, notes, tools, settings' },
      ],
    },
    more: {
      title: 'More',
      cards: {
        calculator: { title: 'Calculator', subtitle: 'Standard and scientific' },
        health: { title: 'Health', subtitle: 'BMI, water, calories' },
        notes: { title: 'Notes', subtitle: 'Write, dictate, protect' },
        todos: { title: 'Todos', subtitle: 'Plan, reorder, complete' },
        tools: { title: 'Utility Tools', subtitle: 'Passwords and extras' },
        settings: { title: 'Settings', subtitle: 'Theme, font, language, lock' },
      },
    },
    todo: {
      title: 'Todo Planner',
      summaryTitle: 'Keep every task in motion',
      summaryBody:
        'Create focused task cards, reorder them anytime, and keep your next priorities easy to reach.',
      listTitle: 'Todo cards',
      itemsLabel: 'items',
      createTitle: 'Create todo',
      editTitle: 'Edit todo',
      createAction: 'Create task',
      saveAction: 'Save task',
      cancelAction: 'Cancel',
      completed: 'Completed',
      pending: 'Pending',
      dueShort: 'Due:',
      updatedLabel: 'Updated',
      titleRequired: 'Add a task title before saving this card.',
      filters: {
        all: 'All',
        open: 'Open',
        done: 'Done',
      },
      stats: {
        total: 'Total',
        open: 'Open',
        done: 'Done',
      },
      priority: {
        low: 'Low',
        medium: 'Medium',
        high: 'High',
      },
      fields: {
        title: 'Title',
        details: 'Details',
        dueDate: 'Due date',
        priority: 'Priority',
      },
      placeholders: {
        title: 'What needs to get done?',
        details: 'Add context, checklist notes, or a quick reminder.',
        dueDate: 'e.g. Today, Apr 18 6:00 PM',
      },
      emptyTitle: 'No todo cards yet',
      emptyBody:
        'Create your first task card and organize the list with the up and down controls whenever priorities shift.',
    },
    settings: {
      title: 'Settings',
      appearance: 'Appearance',
      theme: 'Theme',
      font: 'Font',
      language: 'Language',
      privacy: 'Privacy',
      protectionSection: 'Protection',
      privacySection: 'Privacy & Security',
      supportSection: 'Support',
      darkMode: 'Dark Mode',
      savedSecurely: 'Saved securely',
      vaultTitle: 'Password Vault',
      vaultSetup: 'Set up a vault PIN',
      vaultUnlocked: 'Unlocked for this session',
      vaultLocked: 'Locked',
      createVaultPin: 'Create vault PIN',
      changeVaultPin: 'Change vault PIN',
      createVaultPinHint: 'Protect your vault with a dedicated PIN',
      changeVaultPinHint: 'Update the lock for saved passwords',
      lockVaultNow: 'Lock vault now',
      lockVaultNowHint: 'End this unlocked session immediately',
      permissions: 'Permissions',
      permissionsHint: 'Review app permissions',
      helpFaq: 'Help & FAQ',
      helpFaqHint: 'Get answers',
      protectNotes: 'Protect notes',
      protectNotesHint: 'Require a PIN before opening notes',
      pinLabel: 'Notes PIN',
      pinPlaceholder: 'Enter 4 digits',
      savePin: 'Save PIN',
      lockNow: 'Lock now',
      themeOptions: { auto: 'Auto', light: 'Light', dark: 'Dark' },
      fontOptions: { inter: 'Inter', system: 'System', serif: 'Serif' },
      languageOptions: { en: 'English', fr: 'French', es: 'Spanish' },
      pinSaved: 'PIN saved. Notes protection is active.',
      pinInvalid: 'PIN must be at least 4 digits.',
      pinRequiredFirst: 'Save a PIN before turning on notes protection.',
    },
    notes: {
      lockedTitle: 'Notes locked',
      lockedBody: 'Enter your PIN to view protected notes.',
      unlock: 'Unlock',
      pinMismatch: 'That PIN does not match.',
    },
    health: {
      title: 'Health',
      bmiTitle: 'BMI calculator',
      heightLabel: 'Height (cm)',
      weightLabel: 'Weight (kg)',
      trackerTitle: 'Water and calorie tracker',
      waterGoal: 'Water goal',
      glasses: 'glasses',
      removeGlass: '- Glass',
      addGlass: '+ Glass',
      caloriesToday: 'Calories today',
    },
    password: {
      title: 'New password',
      statusSetup: 'Set up the vault PIN when you save this password.',
      statusUnlocked: 'Vault unlocked. Saving will go straight into your list.',
      statusLocked: 'Vault locked. You will unlock it before the password is stored.',
      siteLabel: 'Site or app',
      sitePlaceholder: 'e.g. GitHub, Gmail, Instagram',
      usernameLabel: 'Username or email',
      usernamePlaceholder: 'Enter the account username',
      generatorTitle: 'Password generator',
      generatorPlaceholder: 'Generate a password',
      options: {
        upper: 'Upper',
        lower: 'Lower',
        number: 'Number',
        symbol: 'Symbol',
      },
      length: 'Length',
      shorter: 'Shorter',
      longer: 'Longer',
      generate: 'Generate',
      copy: 'Copy',
      copied: 'Copied',
      saveTitle: 'Ready to store it?',
      saveBody:
        'Save this generated password to your protected vault with the site and username above.',
      saveToVault: 'Save to vault',
      noSelection: 'Select at least one character group before generating.',
      copyFirst: 'Generate a password first before copying it.',
      copiedSuccess: 'Password copied to clipboard.',
      generateBeforeSave: 'Generate a password before saving it.',
      addSite: 'Add a site or app name so the entry is easy to find later.',
      addUsername: 'Add the username or email for this password.',
    },
    vault: {
      title: 'Password Vault',
      savedPasswords: 'Saved passwords',
      entry: 'entry',
      entries: 'entries',
      secured: 'secured',
      previousPasswords: 'Previous passwords',
      saved: 'saved',
      updated: 'Updated',
      emptyTitle: 'No passwords saved yet',
      emptyBody:
        'Tap the add button to generate a password and store it with a site and username for later.',
      entryTitle: 'Vault Entry',
      lastUpdated: 'Last updated',
      site: 'Site',
      username: 'Username',
      password: 'Password',
      sitePlaceholder: 'Website or app',
      usernamePlaceholder: 'Username or email',
      copyPassword: 'Copy Password',
      copyUsername: 'Copy Username',
      saveChanges: 'Save Changes',
      delete: 'Delete',
      notFoundTitle: 'Password not found',
      notFoundBody:
        'This saved password could not be found. It may have been deleted already.',
      siteEmpty: 'Site or app name cannot be empty.',
      usernameEmpty: 'Username or email cannot be empty.',
      updatedMessage: 'Vault entry updated.',
      lock: {
        createTitle: 'Create Vault PIN',
        changeTitle: 'Change Vault PIN',
        unlockTitle: 'Unlock Vault',
        setupBody:
          'Set a dedicated PIN for your password vault before saving your first password.',
        changeBody: 'Choose a new PIN for the password vault.',
        unlockBodyPending:
          'Enter your vault PIN to save and open the generated password.',
        unlockBodyView: 'Enter your vault PIN to view saved passwords.',
        currentPinFirst: 'Enter your current vault PIN first.',
        currentPinIncorrect: 'Your current vault PIN is incorrect.',
        pinTooShort: 'PIN must be at least 4 digits.',
        pinsNoMatch: 'PINs do not match.',
        pinMismatch: 'That vault PIN does not match.',
        currentPinPlaceholder: 'Current PIN',
        enterPinPlaceholder: 'Enter PIN',
        confirmPinPlaceholder: 'Confirm PIN',
        unlockAction: 'Unlock Vault',
        saveAction: 'Save PIN',
      },
    },
    time: {
      title: 'Time Tools',
      tabs: {
        stopwatch: 'Stopwatch',
        countdown: 'Countdown',
        world: 'World',
      },
      start: 'Start',
      stop: 'Stop',
      pause: 'Pause',
      lap: 'Lap',
      reset: 'Reset',
      presets: 'Presets',
      clockFormat: 'Clock format',
      timeConversion: 'Time conversion',
      from: 'From',
      to: 'To',
    },
    help: {
      title: 'Help & FAQ',
      intro:
        'Find quick answers for the most common app questions and a few tips for using the tools smoothly.',
      questions: [
        {
          question: 'How do I protect my notes?',
          answer:
            'Open Settings, create a Notes PIN, then turn on notes protection. Once enabled, the notes section will request your PIN before opening.',
        },
        {
          question: 'How does the password vault work?',
          answer:
            'Generate a password, add the site and username, then save it to the vault. The vault is protected by its own separate PIN stored securely on the device.',
        },
        {
          question: 'Does currency conversion still work offline?',
          answer:
            'Yes. When the device has no network connection, the converter falls back to offline rates so the screen still remains usable.',
        },
        {
          question: 'Why is microphone permission needed?',
          answer:
            'Microphone access is used for voice note recording and speech-to-text dictation inside the notes editor.',
        },
        {
          question: 'How do I change theme or language?',
          answer:
            'Go to Settings to switch theme preference, font preference, and language. Screens using shared app copy update when the language changes.',
        },
      ],
    },
  },
  fr: {
    tabs: {
      home: 'Accueil',
      calculator: 'Calculatrice',
      calculatorShort: 'Calc',
      converter: 'Convertisseur',
      time: 'Temps',
      more: 'Plus',
    },
    home: {
      title: 'Accueil',
      sectionTitle: 'Outils',
      notesLabel: 'Notes',
      historyLabel: 'Historique',
      enabled: 'Active',
      disabled: 'Desactivee',
      quickActions: [
        { title: 'Convertisseur', subtitle: 'Unites, devises, bases' },
        { title: 'Calculatrice', subtitle: 'Standard et scientifique' },
        { title: 'Temps', subtitle: 'Horloges, minuteur, chrono' },
        { title: 'Plus', subtitle: 'Sante, notes, outils, reglages' },
      ],
    },
    more: {
      title: 'Plus',
      cards: {
        health: { title: 'Sante', subtitle: 'IMC, eau, calories' },
        notes: { title: 'Notes', subtitle: 'Ecrire, dicter, proteger' },
        todos: { title: 'Taches', subtitle: 'Planifier, reordonner, terminer' },
        tools: { title: 'Outils', subtitle: 'Mots de passe et extras' },
        settings: { title: 'Reglages', subtitle: 'Theme, police, langue, verrou' },
      },
    },
    todo: {
      title: 'Planificateur de taches',
      summaryTitle: 'Gardez chaque tache en mouvement',
      summaryBody:
        'Creez des cartes de taches claires, reordonnez-les a tout moment et gardez vos prochaines priorites a portee de main.',
      listTitle: 'Cartes de taches',
      itemsLabel: 'elements',
      createTitle: 'Creer une tache',
      editTitle: 'Modifier la tache',
      createAction: 'Creer la tache',
      saveAction: 'Enregistrer',
      cancelAction: 'Annuler',
      completed: 'Terminee',
      pending: 'En attente',
      dueShort: 'Echeance :',
      updatedLabel: 'Mis a jour',
      titleRequired: 'Ajoutez un titre avant d enregistrer cette carte.',
      filters: {
        all: 'Toutes',
        open: 'Ouvertes',
        done: 'Terminees',
      },
      stats: {
        total: 'Total',
        open: 'Ouvertes',
        done: 'Terminees',
      },
      priority: {
        low: 'Basse',
        medium: 'Moyenne',
        high: 'Haute',
      },
      fields: {
        title: 'Titre',
        details: 'Details',
        dueDate: 'Date limite',
        priority: 'Priorite',
      },
      placeholders: {
        title: 'Que faut-il terminer ?',
        details: 'Ajoutez du contexte, des notes ou un rappel rapide.',
        dueDate: 'ex. Aujourd hui, 18 avr. 18:00',
      },
      emptyTitle: 'Aucune carte de tache',
      emptyBody:
        'Creez votre premiere carte de tache puis reordonnez la liste avec les controles haut et bas quand les priorites changent.',
    },
    settings: {
      title: 'Reglages',
      appearance: 'Apparence',
      theme: 'Theme',
      font: 'Police',
      language: 'Langue',
      privacy: 'Confidentialite',
      protectionSection: 'Protection',
      privacySection: 'Confidentialite et securite',
      supportSection: 'Support',
      darkMode: 'Mode sombre',
      savedSecurely: 'Enregistre en securite',
      vaultTitle: 'Coffre de mots de passe',
      vaultSetup: 'Configurer un PIN de coffre',
      vaultUnlocked: 'Deverrouille pour cette session',
      vaultLocked: 'Verrouille',
      createVaultPin: 'Creer le PIN du coffre',
      changeVaultPin: 'Changer le PIN du coffre',
      createVaultPinHint: 'Protegez votre coffre avec un PIN dedie',
      changeVaultPinHint: 'Mettez a jour la protection des mots de passe',
      lockVaultNow: 'Verrouiller le coffre',
      lockVaultNowHint: 'Terminer immediatement cette session deverrouillee',
      permissions: 'Autorisations',
      permissionsHint: 'Verifier les autorisations de l application',
      helpFaq: 'Aide et FAQ',
      helpFaqHint: 'Obtenir des reponses',
      protectNotes: 'Proteger les notes',
      protectNotesHint: 'Demander un PIN avant ouverture',
      pinLabel: 'PIN des notes',
      pinPlaceholder: 'Entrez 4 chiffres',
      savePin: 'Enregistrer le PIN',
      lockNow: 'Verrouiller',
      themeOptions: { auto: 'Auto', light: 'Clair', dark: 'Sombre' },
      fontOptions: { inter: 'Inter', system: 'Systeme', serif: 'Serif' },
      languageOptions: { en: 'Anglais', fr: 'Francais', es: 'Espagnol' },
      pinSaved: 'PIN enregistre. Protection active.',
      pinInvalid: 'Le PIN doit contenir au moins 4 chiffres.',
      pinRequiredFirst: 'Enregistrez un PIN avant d activer la protection.',
    },
    notes: {
      lockedTitle: 'Notes verrouillees',
      lockedBody: 'Entrez votre PIN pour ouvrir vos notes protegees.',
      unlock: 'Deverrouiller',
      pinMismatch: 'Ce PIN ne correspond pas.',
    },
    health: {
      title: 'Sante',
      bmiTitle: 'Calculateur IMC',
      heightLabel: 'Taille (cm)',
      weightLabel: 'Poids (kg)',
      trackerTitle: 'Suivi eau et calories',
      waterGoal: 'Objectif eau',
      glasses: 'verres',
      removeGlass: '- Verre',
      addGlass: '+ Verre',
      caloriesToday: 'Calories du jour',
    },
    password: {
      title: 'Nouveau mot de passe',
      statusSetup: 'Configurez le PIN du coffre avant de sauvegarder ce mot de passe.',
      statusUnlocked: 'Coffre deverrouille. La sauvegarde ira directement dans votre liste.',
      statusLocked: 'Coffre verrouille. Vous devrez le deverrouiller avant la sauvegarde.',
      siteLabel: 'Site ou application',
      sitePlaceholder: 'ex. GitHub, Gmail, Instagram',
      usernameLabel: 'Nom utilisateur ou email',
      usernamePlaceholder: 'Entrez le nom du compte',
      generatorTitle: 'Generateur de mot de passe',
      generatorPlaceholder: 'Generez un mot de passe',
      options: {
        upper: 'Maj',
        lower: 'Min',
        number: 'Nombre',
        symbol: 'Symbole',
      },
      length: 'Longueur',
      shorter: 'Plus court',
      longer: 'Plus long',
      generate: 'Generer',
      copy: 'Copier',
      copied: 'Copie',
      saveTitle: 'Pret a enregistrer ?',
      saveBody:
        'Enregistrez ce mot de passe dans votre coffre protege avec le site et le nom utilisateur ci-dessus.',
      saveToVault: 'Enregistrer',
      noSelection: 'Selectionnez au moins un groupe de caracteres avant de generer.',
      copyFirst: 'Generez un mot de passe avant de le copier.',
      copiedSuccess: 'Mot de passe copie dans le presse-papiers.',
      generateBeforeSave: 'Generez un mot de passe avant de sauvegarder.',
      addSite: 'Ajoutez un site ou une application pour retrouver cette entree plus tard.',
      addUsername: 'Ajoutez le nom utilisateur ou email pour ce mot de passe.',
    },
    vault: {
      title: 'Coffre de mots de passe',
      savedPasswords: 'Mots de passe enregistres',
      entry: 'entree',
      entries: 'entrees',
      secured: 'protegees',
      previousPasswords: 'Mots de passe precedents',
      saved: 'sauvegardes',
      updated: 'Mis a jour',
      emptyTitle: 'Aucun mot de passe enregistre',
      emptyBody:
        'Touchez le bouton ajouter pour generer un mot de passe et le conserver avec un site et un identifiant.',
      entryTitle: 'Entree du coffre',
      lastUpdated: 'Derniere mise a jour',
      site: 'Site',
      username: 'Identifiant',
      password: 'Mot de passe',
      sitePlaceholder: 'Site web ou application',
      usernamePlaceholder: 'Nom utilisateur ou email',
      copyPassword: 'Copier le mot de passe',
      copyUsername: 'Copier l identifiant',
      saveChanges: 'Enregistrer',
      delete: 'Supprimer',
      notFoundTitle: 'Mot de passe introuvable',
      notFoundBody:
        'Ce mot de passe enregistre est introuvable. Il a peut-etre deja ete supprime.',
      siteEmpty: 'Le nom du site ou de l application ne peut pas etre vide.',
      usernameEmpty: 'Le nom utilisateur ou l email ne peut pas etre vide.',
      updatedMessage: 'Entree du coffre mise a jour.',
      lock: {
        createTitle: 'Creer le PIN du coffre',
        changeTitle: 'Changer le PIN du coffre',
        unlockTitle: 'Deverrouiller le coffre',
        setupBody:
          'Definissez un PIN dedie pour votre coffre avant de sauvegarder votre premier mot de passe.',
        changeBody: 'Choisissez un nouveau PIN pour le coffre.',
        unlockBodyPending:
          'Entrez votre PIN du coffre pour sauvegarder et ouvrir le mot de passe genere.',
        unlockBodyView: 'Entrez votre PIN du coffre pour voir les mots de passe sauvegardes.',
        currentPinFirst: 'Entrez d abord votre PIN actuel.',
        currentPinIncorrect: 'Votre PIN actuel est incorrect.',
        pinTooShort: 'Le PIN doit contenir au moins 4 chiffres.',
        pinsNoMatch: 'Les PIN ne correspondent pas.',
        pinMismatch: 'Ce PIN du coffre ne correspond pas.',
        currentPinPlaceholder: 'PIN actuel',
        enterPinPlaceholder: 'Entrez le PIN',
        confirmPinPlaceholder: 'Confirmez le PIN',
        unlockAction: 'Deverrouiller',
        saveAction: 'Enregistrer le PIN',
      },
    },
    time: {
      title: 'Outils de temps',
      tabs: {
        stopwatch: 'Chrono',
        countdown: 'Minuteur',
        world: 'Monde',
      },
      start: 'Demarrer',
      stop: 'Arreter',
      pause: 'Pause',
      lap: 'Tour',
      reset: 'Reinitialiser',
      presets: 'Presets',
      clockFormat: 'Format horaire',
      timeConversion: 'Conversion horaire',
      from: 'De',
      to: 'Vers',
    },
    help: {
      title: 'Aide et FAQ',
      intro:
        'Trouvez des reponses rapides aux questions les plus courantes et quelques conseils pour utiliser les outils facilement.',
      questions: [
        {
          question: 'Comment proteger mes notes ?',
          answer:
            'Ouvrez Reglages, creez un PIN pour les notes, puis activez la protection. Une fois activee, la section notes demandera votre PIN.',
        },
        {
          question: 'Comment fonctionne le coffre de mots de passe ?',
          answer:
            'Generez un mot de passe, ajoutez le site et le nom utilisateur, puis enregistrez-le dans le coffre. Le coffre utilise son propre PIN securise sur l appareil.',
        },
        {
          question: 'La conversion de devises fonctionne-t-elle hors ligne ?',
          answer:
            'Oui. Quand l appareil est hors ligne, le convertisseur utilise des taux de secours pour rester utilisable.',
        },
        {
          question: 'Pourquoi l application demande-t-elle le microphone ?',
          answer:
            'Le microphone est utilise pour enregistrer des notes vocales et pour la dictee dans l editeur de notes.',
        },
        {
          question: 'Comment changer le theme ou la langue ?',
          answer:
            'Allez dans Reglages pour modifier le theme, la police et la langue. Les ecrans relies au systeme de copie partagent ces changements.',
        },
      ],
    },
  },
  es: {
    tabs: {
      home: 'Inicio',
      calculator: 'Calculadora',
      calculatorShort: 'Calc',
      converter: 'Conversor',
      time: 'Tiempo',
      more: 'Mas',
    },
    home: {
      title: 'Inicio',
      sectionTitle: 'Utilidades',
      notesLabel: 'Notas',
      historyLabel: 'Historial',
      enabled: 'Activa',
      disabled: 'Desactivada',
      quickActions: [
        { title: 'Conversor', subtitle: 'Unidades, monedas, bases' },
        { title: 'Calculadora', subtitle: 'Estandar y cientifica' },
        { title: 'Tiempo', subtitle: 'Relojes, temporizador, cronometro' },
        { title: 'Mas', subtitle: 'Salud, notas, herramientas, ajustes' },
      ],
    },
    more: {
      title: 'Mas',
      cards: {
        health: { title: 'Salud', subtitle: 'IMC, agua, calorias' },
        notes: { title: 'Notas', subtitle: 'Escribir, dictar, proteger' },
        todos: { title: 'Tareas', subtitle: 'Planear, reordenar, completar' },
        tools: { title: 'Herramientas', subtitle: 'Contrasenas y extras' },
        settings: { title: 'Ajustes', subtitle: 'Tema, fuente, idioma, bloqueo' },
      },
    },
    todo: {
      title: 'Planificador de tareas',
      summaryTitle: 'Manten cada tarea en movimiento',
      summaryBody:
        'Crea tarjetas de tareas claras, reordenalas cuando quieras y manten tus prioridades cerca.',
      listTitle: 'Tarjetas de tareas',
      itemsLabel: 'elementos',
      createTitle: 'Crear tarea',
      editTitle: 'Editar tarea',
      createAction: 'Crear tarea',
      saveAction: 'Guardar tarea',
      cancelAction: 'Cancelar',
      completed: 'Completada',
      pending: 'Pendiente',
      dueShort: 'Vence:',
      updatedLabel: 'Actualizada',
      titleRequired: 'Agrega un titulo antes de guardar esta tarjeta.',
      filters: {
        all: 'Todas',
        open: 'Abiertas',
        done: 'Hechas',
      },
      stats: {
        total: 'Total',
        open: 'Abiertas',
        done: 'Hechas',
      },
      priority: {
        low: 'Baja',
        medium: 'Media',
        high: 'Alta',
      },
      fields: {
        title: 'Titulo',
        details: 'Detalles',
        dueDate: 'Fecha limite',
        priority: 'Prioridad',
      },
      placeholders: {
        title: 'Que necesitas terminar?',
        details: 'Agrega contexto, notas o un recordatorio rapido.',
        dueDate: 'ej. Hoy, 18 abr 6:00 PM',
      },
      emptyTitle: 'Todavia no hay tareas',
      emptyBody:
        'Crea tu primera tarjeta y reorganiza la lista con los controles de arriba y abajo cuando cambien las prioridades.',
    },
    settings: {
      title: 'Ajustes',
      appearance: 'Apariencia',
      theme: 'Tema',
      font: 'Fuente',
      language: 'Idioma',
      privacy: 'Privacidad',
      protectionSection: 'Proteccion',
      privacySection: 'Privacidad y seguridad',
      supportSection: 'Soporte',
      darkMode: 'Modo oscuro',
      savedSecurely: 'Guardado de forma segura',
      vaultTitle: 'Vault de contrasenas',
      vaultSetup: 'Configurar un PIN del vault',
      vaultUnlocked: 'Desbloqueado en esta sesion',
      vaultLocked: 'Bloqueado',
      createVaultPin: 'Crear PIN del vault',
      changeVaultPin: 'Cambiar PIN del vault',
      createVaultPinHint: 'Protege tu vault con un PIN dedicado',
      changeVaultPinHint: 'Actualiza la proteccion de las contrasenas guardadas',
      lockVaultNow: 'Bloquear vault ahora',
      lockVaultNowHint: 'Cerrar inmediatamente esta sesion desbloqueada',
      permissions: 'Permisos',
      permissionsHint: 'Revisar permisos de la aplicacion',
      helpFaq: 'Ayuda y FAQ',
      helpFaqHint: 'Obtener respuestas',
      protectNotes: 'Proteger notas',
      protectNotesHint: 'Solicitar PIN antes de abrir notas',
      pinLabel: 'PIN de notas',
      pinPlaceholder: 'Ingresa 4 digitos',
      savePin: 'Guardar PIN',
      lockNow: 'Bloquear ahora',
      themeOptions: { auto: 'Auto', light: 'Claro', dark: 'Oscuro' },
      fontOptions: { inter: 'Inter', system: 'Sistema', serif: 'Serif' },
      languageOptions: { en: 'Ingles', fr: 'Frances', es: 'Espanol' },
      pinSaved: 'PIN guardado. Proteccion activa.',
      pinInvalid: 'El PIN debe tener al menos 4 digitos.',
      pinRequiredFirst: 'Guarda un PIN antes de activar la proteccion.',
    },
    notes: {
      lockedTitle: 'Notas bloqueadas',
      lockedBody: 'Ingresa tu PIN para ver tus notas protegidas.',
      unlock: 'Desbloquear',
      pinMismatch: 'Ese PIN no coincide.',
    },
    health: {
      title: 'Salud',
      bmiTitle: 'Calculadora IMC',
      heightLabel: 'Altura (cm)',
      weightLabel: 'Peso (kg)',
      trackerTitle: 'Control de agua y calorias',
      waterGoal: 'Meta de agua',
      glasses: 'vasos',
      removeGlass: '- Vaso',
      addGlass: '+ Vaso',
      caloriesToday: 'Calorias de hoy',
    },
    password: {
      title: 'Nueva contrasena',
      statusSetup: 'Configura el PIN del vault antes de guardar esta contrasena.',
      statusUnlocked: 'Vault desbloqueado. Se guardara directo en tu lista.',
      statusLocked: 'Vault bloqueado. Debes desbloquearlo antes de guardar.',
      siteLabel: 'Sitio o app',
      sitePlaceholder: 'ej. GitHub, Gmail, Instagram',
      usernameLabel: 'Usuario o correo',
      usernamePlaceholder: 'Ingresa la cuenta',
      generatorTitle: 'Generador de contrasenas',
      generatorPlaceholder: 'Genera una contrasena',
      options: {
        upper: 'May',
        lower: 'Min',
        number: 'Numero',
        symbol: 'Simbolo',
      },
      length: 'Longitud',
      shorter: 'Mas corta',
      longer: 'Mas larga',
      generate: 'Generar',
      copy: 'Copiar',
      copied: 'Copiado',
      saveTitle: 'Listo para guardar?',
      saveBody:
        'Guarda esta contrasena en tu vault protegido con el sitio y usuario indicados arriba.',
      saveToVault: 'Guardar en vault',
      noSelection: 'Selecciona al menos un grupo de caracteres antes de generar.',
      copyFirst: 'Genera una contrasena antes de copiarla.',
      copiedSuccess: 'Contrasena copiada al portapapeles.',
      generateBeforeSave: 'Genera una contrasena antes de guardarla.',
      addSite: 'Agrega un sitio o app para encontrar esta entrada mas tarde.',
      addUsername: 'Agrega el usuario o correo de esta contrasena.',
    },
    vault: {
      title: 'Vault de contrasenas',
      savedPasswords: 'Contrasenas guardadas',
      entry: 'entrada',
      entries: 'entradas',
      secured: 'protegidas',
      previousPasswords: 'Contrasenas anteriores',
      saved: 'guardadas',
      updated: 'Actualizada',
      emptyTitle: 'No hay contrasenas guardadas',
      emptyBody:
        'Toca el boton agregar para generar una contrasena y guardarla con un sitio y usuario.',
      entryTitle: 'Entrada del vault',
      lastUpdated: 'Ultima actualizacion',
      site: 'Sitio',
      username: 'Usuario',
      password: 'Contrasena',
      sitePlaceholder: 'Sitio web o app',
      usernamePlaceholder: 'Usuario o correo',
      copyPassword: 'Copiar contrasena',
      copyUsername: 'Copiar usuario',
      saveChanges: 'Guardar cambios',
      delete: 'Eliminar',
      notFoundTitle: 'Contrasena no encontrada',
      notFoundBody:
        'Esta contrasena guardada no se encontro. Puede que ya haya sido eliminada.',
      siteEmpty: 'El nombre del sitio o app no puede estar vacio.',
      usernameEmpty: 'El usuario o correo no puede estar vacio.',
      updatedMessage: 'Entrada del vault actualizada.',
      lock: {
        createTitle: 'Crear PIN del vault',
        changeTitle: 'Cambiar PIN del vault',
        unlockTitle: 'Desbloquear vault',
        setupBody:
          'Define un PIN dedicado para tu vault antes de guardar tu primera contrasena.',
        changeBody: 'Elige un nuevo PIN para el vault.',
        unlockBodyPending:
          'Ingresa tu PIN del vault para guardar y abrir la contrasena generada.',
        unlockBodyView: 'Ingresa tu PIN del vault para ver las contrasenas guardadas.',
        currentPinFirst: 'Ingresa primero tu PIN actual.',
        currentPinIncorrect: 'Tu PIN actual es incorrecto.',
        pinTooShort: 'El PIN debe tener al menos 4 digitos.',
        pinsNoMatch: 'Los PIN no coinciden.',
        pinMismatch: 'Ese PIN del vault no coincide.',
        currentPinPlaceholder: 'PIN actual',
        enterPinPlaceholder: 'Ingresa el PIN',
        confirmPinPlaceholder: 'Confirma el PIN',
        unlockAction: 'Desbloquear vault',
        saveAction: 'Guardar PIN',
      },
    },
    time: {
      title: 'Herramientas de tiempo',
      tabs: {
        stopwatch: 'Crono',
        countdown: 'Temporizador',
        world: 'Mundo',
      },
      start: 'Iniciar',
      stop: 'Detener',
      pause: 'Pausar',
      lap: 'Vuelta',
      reset: 'Reiniciar',
      presets: 'Presets',
      clockFormat: 'Formato horario',
      timeConversion: 'Conversion de tiempo',
      from: 'Desde',
      to: 'Hacia',
    },
    help: {
      title: 'Ayuda y FAQ',
      intro:
        'Encuentra respuestas rapidas a las preguntas mas comunes y algunos consejos para usar mejor las herramientas.',
      questions: [
        {
          question: 'Como protejo mis notas?',
          answer:
            'Abre Ajustes, crea un PIN para notas y luego activa la proteccion. Cuando este activa, la seccion de notas pedira tu PIN.',
        },
        {
          question: 'Como funciona el vault de contrasenas?',
          answer:
            'Genera una contrasena, agrega el sitio y el usuario, y guardala en el vault. El vault usa su propio PIN guardado de forma segura en el dispositivo.',
        },
        {
          question: 'La conversion de moneda funciona sin internet?',
          answer:
            'Si. Cuando el dispositivo no tiene red, el conversor usa tasas de respaldo para seguir funcionando.',
        },
        {
          question: 'Por que se necesita permiso de microfono?',
          answer:
            'El microfono se usa para grabar notas de voz y para la dictadura por voz dentro del editor de notas.',
        },
        {
          question: 'Como cambio el tema o el idioma?',
          answer:
            'Ve a Ajustes para cambiar tema, fuente e idioma. Las pantallas conectadas al sistema de textos compartidos se actualizan al cambiar el idioma.',
        },
      ],
    },
  },
} as const;

export function useAppCopy() {
  const language = useSettingsStore((state) => state.languagePreference);
  return copy[language];
}
